### ISSUE TITLE
A.A.U.I.W.L Song clues to be accurate to my chosen year

### ISSUE THREAD

**Issue by KH20** [KH20/GuessTheYear#1]
# Issue

## User Story
As a user, I would like the song clues to be accurate to my chosen year so that there's no confusion whilst playing

## Tasks
- [x] Find more reliable datasource to scrape
- [x] Write the code to scrape from new source

## Acceptance Criteria
**Functional Requirements**

- [x] The song clues should all be **RELEASED** in the year given by the user

**Comment by KH20** [comment]
Issue is now completed. Data has been scraped and stored within a local JSON file saving the need to request external sources.
