### ISSUE TITLE
A.A.U.I.W.L Feedback upon submitting a year so that I can be sure my input is accepted

### ISSUE THREAD

**Issue by KH20** [KH20/GuessTheYear#2]
# Issue

## User Story
As a user, I would like feedback upon submitting the year so that I can be sure that my input is accepted.

## Tasks
- [x] Show loading screen while data is being gathered

- [x] Add text confirming the year that was entered.

## Acceptance Criteria
**Functional Requirements**

- [x] The page should become non-interactive upon receiving data, until data is loaded.
- [x] The submitted year should be on display during and after loading.
