### ISSUE TITLE
AAUIWL A pop culture inspired loading icon

### ISSUE THREAD

**Issue by KH20** [KH20/GuessTheYear#7]
# Issue

## User Story
As a user, I would like a loading icon to be movie/music inspired

## Tasks
- [ ] Research loading possibilities using the likes of movie and music inspired pop culture
- [ ] Give user facts about the year in question while the data loads.

## Acceptance Criteria
**Functional Requirements**

- [ ] The loader should be something along the lines of Back to the Future or Superman timetravelling.
