### ISSUE TITLE
AAUIWL The app to have offline functionality

### ISSUE THREAD

**Issue by KH20** [KH20/GuessTheYear#8]
# Issue

## User Story
As a user, I would like the application to be useable offline.

## Tasks
- [x] Create a dataset range to be downloaded for offline use
- [x] Use Local Storage to store the data
- [x] Modify current load algorithm to check local storage before scraping new data
- [x] Ensure functionality for multiple music genres 

## Acceptance Criteria
**Functional Requirements**
- [x] The application should function as normal with no connection
- [x] The application should not regather data if data forn the year in question exists
